task :test => [] do
  sh "ruby ios7crypt.rb -e monkey"
  sh "ruby ios7crypt.rb -d 12140a19190e15"
end

task :reek => [] do
  sh "bundle exec reek -q .; true"
end

task :flay => [] do
  sh "bundle exec flay ."
end

task :roodi => [] do
  sh "bundle exec roodi -config=roodi.yml *.rb **/*.rb"
end

task :cane => [] do
  sh "bundle exec cane -f *.rb; bundle exec cane **/*.rb"
end

task :excellent => [] do
  sh "bundle exec excellent ."
end

task :rubocop => [] do
  sh "bundle exec rubocop"
end

task :lint => [:reek, :flay, :roodi, :cane, :excellent, :rubocop] do
end

task :flog => [] do
  sh "bundle exec flog ."
end

task :churn => [] do
  sh "bundle exec churn"
end
